from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent


TRAINING_PARAMS = {'PROCESSED_ROOT': 'data/processed/Immunotherapy',
 'OUTPUT_DIR': 'outputs/Immunotherapy',
 'QWEN_MODEL_PATH': 'Qwen/Qwen2.5-1.5B-Instruct',
 'TIME_POINTS': [1990, 2000, 2005, 2010, 2014, 2017, 2019, 2020, 2021, 2022, 2023, 2024],
 'INIT_TRAIN_TIMES': [2000, 2005, 2010, 2014, 2017],
 'JOINT_TRAIN_TIMES': [2019, 2020, 2021, 2022, 2023],
 'CANDIDATE_MAX_SIZE': 256,
 'HIDDEN_DIM': 256,
 'NUM_HEADS': 4,
 'SET_ATTN_LAYERS': 1,
 'DROPOUT': 0.1,
 'USE_PAIR_QUERY_TOKENS': False,
 'USE_CANDIDATE_QUERY_CROSS_ATTN': True,
 'USE_SIDE_EMBEDDING': True,
 'USE_ENHANCED_STOP': True,
 'CANDIDATE_QUERY_ATTN_CHUNK_SIZE': 2048,
 'ANES_BATCH_SIZE': 128,
 'ANES_NUM_WORKERS': 4,
 'PIN_MEMORY': True,
 'PERSISTENT_WORKERS': True,
 'PREFETCH_FACTOR': 4,
 'INIT_EPOCHS_PER_TIME': 4,
 'JOINT_ANES_WEAK_EPOCHS_PER_TIME': 2,
 'ANES_INIT_LR': 0.0002,
 'ANES_WEAK_LR': 0.0001,
 'ANES_FEEDBACK_LR': 5e-05,
 'WEIGHT_DECAY': 0.0001,
 'GRAD_CLIP': 1.0,
 'MARGIN': 0.5,
 'LAMBDA_NEG': 1.0,
 'LAMBDA_RANK': 0.2,
 'LAMBDA_LEN': 0.0,
 'LAMBDA_PSEUDO': 0.0,
 'ANES_AMP': True,
 'ANES_AMP_DTYPE': 'bfloat16',
 'ENABLE_QWEN_LORA_IN_JOINT_STAGE': True,
 'LORA_TRAIN_POS_N': 10000,
 'LORA_TRAIN_NEG_N': 10000,
 'LORA_EPOCHS': 1,
 'LORA_BATCH_SIZE': 4,
 'LORA_GRAD_ACCUM': 8,
 'LORA_LR': 5e-05,
 'LORA_CONTEXT_LIMIT': 8192,
 'LORA_TORCH_DTYPE': 'auto',
 'LORA_GRADIENT_CHECKPOINTING': False,
 'LORA_FAIL_ON_HIGH_NAN_RATIO': True,
 'LORA_MAX_NAN_RATIO': 0.05,
 'ENABLE_LLM_FEEDBACK': True,
 'JOINT_ROUNDS_PER_TIME': 5,
 'FEEDBACK_TRAIN_POS_N': 1000,
 'FEEDBACK_TRAIN_NEG_N': 1000,
 'FEEDBACK_EPOCHS': 1,
 'FEEDBACK_BATCH_SIZE': 4,
 'FEEDBACK_NUM_WORKERS': 0,
 'FEEDBACK_NUM_SAMPLED_SETS': 4,
 'FEEDBACK_INCLUDE_DETERMINISTIC_SET': True,
 'FEEDBACK_INCLUDE_WEAK_SET': True,
 'FEEDBACK_GUMBEL_TEMPERATURE': 0.7,
 'FEEDBACK_BETA_LENGTH': 0.0,
 'FEEDBACK_GAMMA_REDUNDANCY': 0.0,
 'FEEDBACK_LAMBDA_ANCHOR': 0.0,
 'FEEDBACK_LAMBDA_DISTILL': 0.2,
 'FEEDBACK_SCORE_BATCH_SIZE': 8,
 'FEEDBACK_MAX_INVALID_SCORE_RATIO': 0.02,
 'FEEDBACK_FAIL_ON_INVALID_SCORE': True,
 'FEEDBACK_MIN_REWARD_SPREAD': 1e-06,
 'QWEN_TORCH_DTYPE': 'auto',
 'LLM_CONTEXT_LIMIT': 8192,
 'EVIDENCE_K_MAX': 8,

 'VALIDATION_BATCH_SIZE': 8,
 'VALIDATION_SCORE_BATCH_SIZE': 8,
 'RESUME': True,
 'RESUME_LOAD_COMPLETED_STAGE_CKPT': True,
 'SAVE_ANES_EVERY_EPOCH': True,
 'REMOVE_INCOMPLETE_LORA_ON_RESUME': True,
 'SEED': 2026,
 'SHOW_PROGRESS': True,
 'DEVICE': 'auto',
 'ALLOW_TF32': True}


def main():
    from jtrag.training import main as train
    params = dict(TRAINING_PARAMS)
    for key in ("PROCESSED_ROOT", "OUTPUT_DIR"):
        params[key] = str((REPO_ROOT / params[key]).resolve())
    local_qwen = REPO_ROOT / "models/Qwen2.5-1.5B-Instruct"
    if local_qwen.is_dir():
        params["QWEN_MODEL_PATH"] = str(local_qwen)
    return train(params)


if __name__ == "__main__":
    raise SystemExit(main())
